warning( "This file has been generated by Monkey Studio (2006.1.6.0) - http://sourceforge.net/projects/monkeystudio" )

include( ../../plugins.inc )

TEMPLATE 	= lib
LANGUAGE	= C++
CONFIG	+= warn_on release lib_bundle thread x11 dll plugin
DESTDIR	= $$MONKEY_PLUGINS_DIR/base
TARGET	= QFileBrowser
RESOURCES	+= src/resources/QFileBrowser.qrc

SOURCES	= src/QFileBrowser.cpp \
	src/pFileBrowser.cpp

HEADERS = src/QFileBrowser.h \
	src/pFileBrowser.h
