#include "../src/pluginsmanager/BasePlugin.h"
#include "../src/pluginsmanager/XUPPlugin.h"
#include "../src/pluginsmanager/BuilderPlugin.h"
#include "../src/pluginsmanager/ChildPlugin.h"
#include "../src/pluginsmanager/CLIToolPlugin.h"
#include "../src/pluginsmanager/CompilerPlugin.h"
#include "../src/pluginsmanager/DebuggerPlugin.h"
#include "../src/pluginsmanager/InterpreterPlugin.h"
#include "../src/pluginsmanager/PluginsManager.h"
#include "../src/pluginsmanager/WorkspacePlugin.h"

#include "../src/pluginsmanager/ui/UIBuilderSettings.h"
#include "../src/pluginsmanager/ui/UICLIToolSettings.h"
#include "../src/pluginsmanager/ui/UICompilerSettings.h"
#include "../src/pluginsmanager/ui/UIPluginsSettings.h"
